"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Habito_1 = require("./Habito");
const Usuario_1 = require("./Usuario");
const ControlHabitos_1 = require("./ControlHabitos");
const usuario1 = new Usuario_1.Usuario(1, "Jean Pierre");
const habito1 = new Habito_1.Habito(101, "Beber agua", "Hidratación", "Tomar 8 vasos de agua");
const app = new ControlHabitos_1.ControlHabitos();
app.agregarUsuario(usuario1);
app.registrarHabito(usuario1.id, habito1);
console.log("Aplicación cargada correctamente");
